# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3cc8e90c140aee55466b2377664d427e1d7c70cc2a6e40f57362a731f1acbad942e2d0a02926bddf16b2acf863fb6433d3918cfc229247f772b2b90b742b589

test:
  secret_key_base: 916d067c2700c2e2da4ac03f94fb27e9220089e4d1a42ddc4fcf973eae266a5b36e3d25ef76c1757cd30931cb52f9250de964572e7b9e44eb7ecacc914c87fe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
